service:
  name: WyreCostAverage

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  account:
    handler: account.handler
    events:
      - http:
          method: get
          path: account
          cors: true
      - http:
          method: post
          path: account
          cors: true
      - http:
          method: post
          path: account/document
          cors: true
        
